site_name: Welcome
site_description: This is for documentation
site_url: https://kb.fathurrahman.my
theme: 
  font:
    text: Courier
    code: Roboto Mono
  name: material
  palette: 
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Dark mode
      primary: black
      accent: indigo

    # Light Mode
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Light mode
      primary: black
      accent: deep orange
  
## Navigation tab confifuration
  features:
    #- navigation.instant
    #- navigation.instant.progress
    #- navigation.tracking
    - navigation.tabs
    - navigation.indexes
    #- navigation.tabs.sticky
    #- navigation.sections
    #- navigation.expand
    #- toc.follow
    - toc.integrate

## Nav bar sitemap
nav:
  - Home: index.md
  - Whois: hello.md
  - KB: ./blog

## Coding markdown configuration
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
## Searchbar
  - search:
## Blog setup
  - blog:
      blog_toc: 
      post_url_format: "{slug}"

      
## Hide default mkdocs copyright
extra:
  generator: false

## Custom copyright
copyright: Copyright &copy; Kontolodon