site_name: Fathurrahman Azman
site_url: https://kb.fathurrahman.my
theme:
  font:
    text: Courier
    code: Roboto Mono
  logo: assets/command-palette-24.svg
  name: material
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Light mode
      primary: indigo
      accent: indigo

    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Dark mode
      primary: indigo
      accent: indigo

  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    # - toc.integrate
    - navigation.top

nav:
  - Home: index.md
  - whoami: who.md
  - AWS: tags-aws.md
  - HomeLab: tags-homelab.md
  - Blog: blog

plugins:
  - blog:
      categories: true
  - search:
  - tags



extra:
  generator: false

## Custom copyright
copyright: Copyright &copy; Kontolodon